export const mockData = [
  {
    id: 1,
    organization: "Company A",
    position:
      "Software Engineer Software Engineer  Software Engineer  Software Engineer",
    location: "Makati, Philippines",
    workArrangement: "Remote",
    source: { platform: "LinkedIn", link: "#" },
    salary: "30,000-40,000",
    status: "applied",
    date: "2025-05-10",
  },
  {
    id: 2,
    organization: "Company B",
    position: "Data Scientist",
    location: "Makati, Philippines",
    workArrangement: "Remote",
    source: { platform: "Indeed", link: "#" },
    salary: "30,000-40,000",
    status: "interviewing",
    date: "2024-04-22",
  },
  {
    id: 3,
    organization: "Company C",
    position: "Product Manager",
    location: "Makati, Philippines",
    workArrangement: "Hybrid",
    source: { platform: "JobStreet", link: "#" },
    salary: "30,000-40,000",
    status: "offered",
    date: "2024-03-15",
  },
  {
    id: 4,
    organization: "Company D",
    position: "UX Designer",
    location: "Makati, Philippines",
    workArrangement: "Remote",
    source: { platform: "JobStreet", link: "#" },
    salary: "50,000-80,000",
    status: "rejected",
    date: "2024-02-28",
  },
];
